# Generated by Django 4.2.7 on 2023-11-21 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes',
            name='fechaPedido',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 6, 3, 52, 202369, tzinfo=datetime.timezone.utc)),
        ),
    ]
