# Generated by Django 4.2.4 on 2023-09-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevousuario',
            name='Numero',
            field=models.IntegerField(),
        ),
    ]
