# Generated by Django 4.2.7 on 2023-11-16 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='calle',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='col_mun',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='colonia',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='n_seg_social',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='num_ext',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='num_int',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rfc',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='t_sangre',
        ),
    ]
