# Generated by Django 4.2.7 on 2023-11-16 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0002_rename_calle_usuario_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='num_tel',
        ),
    ]
