# Generated by Django 4.2.7 on 2023-11-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0003_remove_usuario_num_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='descripcion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
