# Generated by Django 4.2.7 on 2023-11-16 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0004_alter_usuario_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='curp',
        ),
    ]
