# Generated by Django 4.2.6 on 2023-11-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0005_remove_usuario_curp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolextra',
            name='soporteenviar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolextra',
            name='usuariosRecuperacion',
            field=models.BooleanField(default=False),
        ),
    ]
