# Generated by Django 4.2.6 on 2023-11-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0006_rolextra_soporteenviar_rolextra_usuariosrecuperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolextra',
            name='pedidos',
            field=models.BooleanField(default=False),
        ),
    ]
