# Generated by Django 4.2.6 on 2023-10-16 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0022_productos_id_proveedores'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='fecha_edit',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='hora_baja',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='movimiento',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='useredit',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
