# Generated by Django 4.2.6 on 2023-10-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0024_alter_productos_id_proveedores'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='status_mov',
            field=models.BooleanField(default=True),
        ),
    ]
