# Generated by Django 4.2.6 on 2023-10-17 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0025_productos_status_mov'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('idhistorial', models.AutoField(primary_key=True, serialize=False)),
                ('movimiento', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('nombre', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mensajes',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mensajes',
            name='status_mov',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mensajes',
            name='tiem_res',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
