# Generated by Django 4.2.6 on 2023-10-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0027_categoria_fech_cate_categoria_movi_categoria_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='admincont',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
