# Generated by Django 4.2.6 on 2023-10-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0028_mensajes_admincont'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='estatus_mov',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
    ]
