# Generated by Django 4.2.6 on 2023-10-17 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0029_proveedores_estatus_mov_alter_proveedores_estatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedores',
            name='estatus_mov',
        ),
    ]
