# Generated by Django 4.2.6 on 2023-10-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0030_remove_proveedores_estatus_mov'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='estatus_mov',
            field=models.BooleanField(default=True),
        ),
    ]
