# Generated by Django 4.2.6 on 2023-10-17 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0031_proveedores_estatus_mov'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedores',
            old_name='estatus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='proveedores',
            old_name='estatus_mov',
            new_name='status_mov',
        ),
    ]
