# Generated by Django 4.2.6 on 2023-10-17 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0032_rename_estatus_proveedores_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedores',
            old_name='status_mov',
            new_name='estatus_mov',
        ),
    ]
