# Generated by Django 4.2.6 on 2023-10-17 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0035_alter_mensajes_status_alter_mensajes_status_mov'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajes',
            old_name='status',
            new_name='estatus',
        ),
    ]
