# Generated by Django 4.2.6 on 2023-10-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0036_rename_status_mensajes_estatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='estatus',
        ),
        migrations.AddField(
            model_name='mensajes',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='status_mov',
            field=models.BooleanField(default=True),
        ),
    ]
