# Generated by Django 4.2.6 on 2023-10-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0037_remove_mensajes_estatus_mensajes_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='cp',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
