# Generated by Django 4.2.6 on 2023-10-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0038_alter_proveedores_cp_alter_proveedores_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='cp',
            field=models.PositiveBigIntegerField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='telefono',
            field=models.PositiveBigIntegerField(max_length=10),
        ),
    ]
