# Generated by Django 4.2.6 on 2023-10-27 22:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0039_alter_proveedores_cp_alter_proveedores_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('marca_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('movi', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('fech_cate', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('status', models.BooleanField(default=True)),
                ('status_mov', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='id_marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='StockMaster_app.marca'),
            preserve_default=False,
        ),
    ]
