# Generated by Django 4.2.6 on 2023-10-27 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0040_marca_productos_id_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='marca',
        ),
    ]
