# Generated by Django 4.2.6 on 2023-11-03 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0042_alter_productos_id_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='id_Proveedores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StockMaster_app.proveedores'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='id_marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StockMaster_app.marca'),
        ),
    ]
