# Generated by Django 4.2.7 on 2023-11-03 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StockMaster_app', '0043_alter_productos_id_proveedores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=255)),
                ('colonia', models.CharField(max_length=255)),
                ('num_ext', models.IntegerField()),
                ('num_int', models.IntegerField(null=True)),
                ('cp', models.IntegerField(null=True)),
                ('col_mun', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('num_tel', models.IntegerField(null=True)),
                ('mun_cel', models.IntegerField()),
                ('curp', models.CharField(max_length=18)),
                ('t_sangre', models.CharField(max_length=4)),
                ('rfc', models.CharField(max_length=13)),
                ('n_seg_social', models.CharField(max_length=11)),
                ('imagen', models.BinaryField(blank=True, null=True)),
                ('permiso', models.BooleanField(default=True)),
                ('cambio', models.BooleanField(default=True)),
                ('comen', models.CharField(max_length=150)),
                ('id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
