# Generated by Django 4.2.6 on 2023-11-05 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0046_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='fech_cate',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='movi',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='status_mov',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='username',
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StockMaster_app.roles'),
        ),
    ]
