# Generated by Django 4.2.6 on 2023-11-05 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0048_roles_fech_cate_roles_movi_roles_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
