# Generated by Django 4.2.6 on 2023-11-07 03:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('StockMaster_app', '0049_remove_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolExtra',
            fields=[
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.group')),
                ('principal', models.BooleanField(default=False)),
                ('inventario', models.BooleanField(default=False)),
                ('productos', models.BooleanField(default=False)),
                ('proveedores', models.BooleanField(default=False)),
                ('etiquetas', models.BooleanField(default=False)),
                ('productosRecuperacion', models.BooleanField(default=False)),
                ('proveedoresRecuperacion', models.BooleanField(default=False)),
                ('etiquetasRecuperacion', models.BooleanField(default=False)),
                ('usuarios', models.BooleanField(default=False)),
                ('roles', models.BooleanField(default=False)),
                ('soporte', models.BooleanField(default=False)),
                ('movi', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('fech_cate', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('status', models.BooleanField(default=True)),
                ('status_mov', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
