# Generated by Django 4.2.6 on 2023-11-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0050_rolextra_delete_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolextra',
            name='contra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolextra',
            name='historialEliminados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolextra',
            name='historialGeneral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolextra',
            name='historialModificaciones',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolextra',
            name='historialMovimientos',
            field=models.BooleanField(default=False),
        ),
    ]
