# Generated by Django 4.2.6 on 2023-11-12 01:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0051_rolextra_contra_rolextra_historialeliminados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('movi', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('fech_cate', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('status', models.BooleanField(default=True)),
                ('status_mov', models.BooleanField(default=True)),
            ],
        ),
    ]
