# Generated by Django 4.2.6 on 2023-11-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0052_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolextra',
            name='designadoRecuperacion',
            field=models.BooleanField(default=False),
        ),
    ]
