# Generated by Django 4.2.6 on 2023-11-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0053_rolextra_designadorecuperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolextra',
            name='area',
            field=models.BooleanField(default=False),
        ),
    ]
