# Generated by Django 4.2.6 on 2023-11-12 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0054_rolextra_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='id_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StockMaster_app.area'),
        ),
    ]
