# Generated by Django 4.2.7 on 2023-11-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0002_alter_nuevousuario_numero'),
        ('StockMaster_app', '0002_persona_delete_nuevousuario'),
        ('StockMaster_app', '0055_productos_id_area'),
    ]

    operations = [
    ]
